// src/site/widgets/custom-elements/components-wrapper/ProductCard.tsx
import React, { useState, useMemo } from 'react';
import { CatalogAPI, type PartialProduct } from './api';
import styles from './element.module.css';

interface ProductCardProps {
  product: PartialProduct;
  onImageClick?: (product: PartialProduct) => void;
  onAddToCart?: (product: PartialProduct) => void;
}

export function ProductCard({ product, onImageClick, onAddToCart }: ProductCardProps) {
  const [imageError, setImageError] = useState(false);
  
  const imageUrl = useMemo(() => {
    return CatalogAPI.buildImageUrl(product.image, 260, 260);
  }, [product.image]);
  
  const handleImageError = () => {
    setImageError(true);
  };

  const handleImageClick = () => {
    console.log('ProductCard image clicked:', product.id);
    if (onImageClick) {
      onImageClick(product);
    } else {
      console.log('No onImageClick handler provided');
    }
  };

  const handleAddToCart = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onAddToCart) {
      onAddToCart(product);
    }
  };

  const handleKeyUp = (e: React.KeyboardEvent, action: 'image' | 'cart') => {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      if (action === 'image') {
        handleImageClick();
      } else if (action === 'cart') {
        handleAddToCart(e as any);
      }
    }
  };
  
  return (
    <div className={styles.productCard}>
      <div 
        className={styles.productImageContainer}
        role="button"
        tabIndex={0}
        onClick={handleImageClick}
        onKeyUp={(e) => handleKeyUp(e, 'image')}
      >
        <img 
          className={styles.productImage}
          src={imageUrl} 
          alt={`${product.artist} - ${product.title}`}
          loading="lazy"
          onError={handleImageError}
        />
        {product.ribbon && (
          <div className={styles.ribbon}>
            <p>{product.ribbon}</p>
          </div>
        )}
      </div>
      <div className={styles.productInfo}>
        <div className={styles.namePanel}>
          <a>{`${product.artist} - ${product.title}`}</a>
        </div>
        <div className={styles.pricePanel}>
          <a className={styles.priceText}>₪{product.price?.toFixed(2) ?? '0.00'}</a>
          <div 
            className={`${styles.btn} ${styles.btnPrice}`}
            role="button"
            tabIndex={0}
            onClick={handleAddToCart}
            onKeyUp={(e) => handleKeyUp(e, 'cart')}
          >
            הוספה לסל
          </div>
        </div>
      </div>
    </div>
  );
}

// src/site/widgets/custom-elements/components-wrapper-lit/ProductCard.tsx
import { html, LitElement } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { CatalogAPI, type Product } from './api';
import { loadedSharedStyles, loadedCardStyles } from './styles-loader';

const FALLBACK_IMAGE = "https://static.wixstatic.com/media/614034_103e8f4ab0ae4536a38b319d3eb437ed~mv2.png/v1/fill/w_260,h_260,al_c,q_85,enc_auto/a.jpg";

@customElement('product-card-lit')
export class ProductCard extends LitElement {
  static styles = [loadedSharedStyles, loadedCardStyles];

  @property({ type: Object })
  product!: Product;

  @state()
  private imageError = false;

  private get imageUrl() {
    if (!this.product?.image || this.product.image.trim() === '' || this.imageError) {
      return FALLBACK_IMAGE;
    }
    return CatalogAPI.buildImageUrl(this.product.image);
  }

  private handleImageError = () => {
    this.imageError = true;
  };

  private handleAddToCart = () => {
    console.log('Adding to cart:', this.product);
  };

  render() {
    if (!this.product) {
      return html``;
    }

    return html`
      <div class="productCard">
        <div class="productImage">
          <img 
            src=${this.imageUrl} 
            alt="${this.product.artist} - ${this.product.title}"
            loading="lazy"
            @error=${this.handleImageError}
          />
        </div>
        <div class="productInfo">
          <h3 class="productArtist">${this.product.artist}</h3>
          <p class="productTitle">${this.product.title}</p>
          <div class="productPrice">₪ ${this.product.price.toFixed(2)}</div>
          <button class="addToCartButton" @click=${this.handleAddToCart}>
            הוסף לסל
          </button>
        </div>
      </div>
    `;
  }
}
